global:
  scrape_interval: 5s

scrape_configs:
  # 1. NestJS High-Level Metrics (HTTP counts, duration)
  - job_name: 'baghaei-backend-http'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['backend:8000']

  # 2. OpenTelemetry Low-Level Metrics (CPU, Memory, Event Loop)
  - job_name: 'baghaei-backend-otel'
    static_configs:
      - targets: ['backend:9464']
